apiVersion: v1
kind: Service
metadata:
  name: {{ include "wire-socket.fullname" . }}
  labels:
    {{- include "wire-socket.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.api.port }}
      targetPort: {{ .Values.service.ports.api.targetPort }}
      protocol: {{ .Values.service.ports.api.protocol }}
      name: api
    - port: {{ .Values.service.ports.tunnel.port }}
      targetPort: {{ .Values.service.ports.tunnel.targetPort }}
      protocol: {{ .Values.service.ports.tunnel.protocol }}
      name: tunnel
    - port: {{ .Values.service.ports.wireguard.port }}
      targetPort: {{ .Values.service.ports.wireguard.targetPort }}
      protocol: {{ .Values.service.ports.wireguard.protocol }}
      name: wireguard
  selector:
    {{- include "wire-socket.selectorLabels" . | nindent 4 }}
