apiVersion: v2
name: wire-socket
description: A Helm chart for WireSocket VPN Server
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - vpn
  - wireguard
  - websocket
home: https://github.com/k0ngk0ng/wire-socket
sources:
  - https://github.com/k0ngk0ng/wire-socket
maintainers:
  - name: k0ngk0ng
